GET http://localhost:1337/todos
###

POST http://localhost:1337/todos
Content-Type: application/json

{
  "name": "Task # 1"
}
###
GET http://localhost:1337/todos/5ec5a63f0085b2aa00dcb16c
###

PUT http://localhost:1337/todos/5ec5a63f0085b2aa00dcb16c
Content-Type: application/json

{
  "completed": true
}
###
DELETE http://localhost:1337/todos/5ec5a63600389a7f00dcb16b
Content-Type: application/json