GET http://localhost:1337/todos
###

POST http://localhost:1337/todos
Content-Type: application/json

{
  "name": "Task # 1"
}
###
GET http://localhost:1337/todos/5ec58b9d0052a069007b6828
###

PUT http://localhost:1337/todos/5ec58b9d0052a069007b6828
Content-Type: application/json

{
  "completed": true
}
###
DELETE http://localhost:1337/todos/5ec5903a00be8a4600be74c5
Content-Type: application/json